src/main/java/com/control/back/halo/basic/beans/DateEditor.java
package com.control.back.halo.basic.beans;

import java.beans.PropertyEditorSupport;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Optional;

import org.apache.commons.lang3.time.DateUtils;

/**
 * Created by zhaohl on 2015/5/8.
 */
public class DateEditor extends PropertyEditorSupport {

    private boolean emptyAsNull;
    private String dateFormat = "yyyy-MM-dd HH:mm:ss";
    public static final String[] DATE_PATTERNS = { "yyyy", "yyyy-MM", "yyyyMM", "yyyy/MM", "yyyy-MM-dd", "yyyyMMdd",
            "yyyy/MM/dd", "yyyy-MM-dd HH:mm:ss", "yyyyMMddHHmmss", "yyyy/MM/dd HH:mm:ss" };

    public DateEditor(boolean emptyAsNull) {
        this.emptyAsNull = emptyAsNull;
    }

    public DateEditor(boolean emptyAsNull, String dateFormat) {
        this.emptyAsNull = emptyAsNull;
        this.dateFormat = dateFormat;
    }

    public String getAsText() {
        Date date = (Date) getValue();
        return Optional.ofNullable(date).map(new SimpleDateFormat(this.dateFormat)::format).orElse("");
    }

    public void setAsText(String text) {
        if (text == null) {
            setValue(null);
        } else {
            String str = text.trim();
            if ((this.emptyAsNull) && ("".equals(str)))
                setValue(null);
            else
                try {
                    setValue(DateUtils.parseDate(str, DATE_PATTERNS));
                } catch (ParseException e) {
                    setValue(null);
                }
        }
    }
}

src/main/java/com/control/back/halo/basic/entity/BaseEntity.java
package com.control.back.halo.basic.entity;

import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;

import org.hibernate.validator.constraints.Length;
import org.springframework.data.jpa.domain.AbstractAuditable;

import com.control.back.halo.basic.listener.BaseEntityListener;

@MappedSuperclass
@EntityListeners({ BaseEntityListener.class })
public abstract class BaseEntity extends AbstractAuditable<User, Long> {

    private String delFlag = DEL_FLAG_NORMAL; // 删除标记（0：正常；1：删除；2：审核）

    public static final String FIELD_DEL_FLAG = "delFlag";
    public static final String DEL_FLAG_NORMAL = "0";
    public static final String DEL_FLAG_DELETE = "1";
    public static final String DEL_FLAG_AUDIT = "2";


    public void setId(Long id) {
        super.setId(id);
    }

    @Length(min = 1, max = 1)
    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

}

src/main/java/com/control/back/halo/basic/entity/User.java
package com.control.back.halo.basic.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "sys_user")
public class User extends BaseEntity {

    private String username;
    private String password;
    /**
     * 最后一次登录时间
     */
    private Date lastLoginTime;
    private String loginIp;

    @Column(nullable = false, updatable = false, unique = true)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(nullable = false)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((username == null) ? 0 : username.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        User other = (User) obj;
        if (username == null) {
            if (other.username != null)
                return false;
        } else if (!username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "Admin{" + "username='" + username + '\'' + ", password='" + password + '\'' + ", lastLoginTime:"
                + lastLoginTime + ", loginIp='" + loginIp + '\'' + '}';
    }

    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}

src/main/java/com/control/back/halo/basic/entity/vo/TreeNode.java
package com.control.back.halo.basic.entity.vo;

import java.io.Serializable;

/**
 * 树型节点<br>
 * 
 * @author halo
 * @see
 * @since V1.0
 */
public class TreeNode implements Serializable {

    /**
     */
    private static final long serialVersionUID = -693675736472494761L;

    /**
     * 节点ID
     **/
    private Long              id;

    /**
     * 节点名称
     **/
    private String            name;

    /**
     * 父节点ID
     **/
    private Long              pid;

    /**
     * 组织类型
     **/
    private int               type;

    private int               status           = 1;

    private String            iconSkin         = "";

    private boolean           isParent         = true;

    private boolean           checked          = false;

    private boolean           open             = false;

    public boolean isOpen() {
        return open;
    }

    public void setOpen(boolean open) {
        this.open = open;
    }

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    /**
     * 
     */
    public TreeNode() {
        super();
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     *            the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the pid
     */
    public Long getPid() {
        return pid;
    }

    /**
     * @param pid
     *            the pid to set
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * @return the type
     */
    public int getType() {
        return type;
    }

    /**
     * @param type
     *            the type to set
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * @return the iconSkin
     */
    public String getIconSkin() {
        return iconSkin;
    }

    /**
     * @param iconSkin
     *            the iconSkin to set
     */
    public void setIconSkin(String iconSkin) {
        this.iconSkin = iconSkin;
    }

    /**
     * @return the status
     */
    public int getStatus() {
        return status;
    }

    /**
     * @param status
     *            the status to set
     */
    public void setStatus(int status) {
        this.status = status;
    }

    public boolean isParent() {
        return isParent;
    }

    public void setParent(boolean isParent) {
        this.isParent = isParent;
    }

}

src/main/java/com/control/back/halo/basic/controller/BaseController.java
package com.control.back.halo.basic.controller;

import java.util.Date;

import org.springframework.beans.propertyeditors.StringTrimmerEditor;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;

import com.control.back.halo.basic.beans.DateEditor;

/**
 * Created by zhaohl on 2015/5/8.
 */
public class BaseController {

    protected static final String ERROR_PAGE = "/admin/common/error";

    @InitBinder
    protected void initBinder(WebDataBinder webDataBinder) {
        webDataBinder.registerCustomEditor(String.class, new StringTrimmerEditor(true));
        webDataBinder.registerCustomEditor(Date.class, new DateEditor(true));
    }
}

src/main/resources/templates/authorization/login.ftl
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">

    <title>登录</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">haloSys</h1>
            </div>
            <h3>欢迎使用 halo.System</h3>

            <form class="m-t" role="form" method="post" action="/login/submit.htm">
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="用户名" required>
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="密码" required>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
     <!--            <p class="text-muted text-center"> 
                	<a href="login.html#"><small>忘记密码了？</small></a> | <a href="register.html">注册一个新账号</a>
                </p> -->
            </form>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/js/jquery.min.js?v=2.1.4"></script>
    <script src="/js/bootstrap.min.js?v=3.4.0"></script>
</body>
</html>

src/main/resources/templates/authorization/register.ftl
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">

    <title>注册</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link href="/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">haloSys</h1>

            </div>
            <h3>欢迎注册 halo.System</h3>
            <p>创建一个halo.System新账户</p>
            <form class="m-t" role="form" action="login.html">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入用户名" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="请输入密码" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="请再次输入密码" required="">
                </div>
                 <div class="form-group text-left">
                    <div class="checkbox i-checks">
                        <label class="no-padding">
                            <input type="checkbox"><i></i> 我同意注册协议</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">注 册</button>

                <p class="text-muted text-center"><small>已经有账户了？</small><a href="login.html">点此登录</a>
                </p>

            </form>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/js/jquery.min.js?v=2.1.4"></script>
    <script src="/js/bootstrap.min.js?v=3.4.0"></script>
    <!-- iCheck -->
    <script src="/js/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
</body>
</html>

src/main/resources/templates/authorization/roleIndex.ftl
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<title>角色授权</title>
<link href="/css/bootstrap.min.css?v=3.3.6"
	rel="stylesheet">
<link href="/css/font-awesome.min.css?v=4.4.0"
	rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0" rel="stylesheet">
<link
	href="//cdn.bootcss.com/zTree.v3/3.5.24/css/zTreeStyle/zTreeStyle.css"
	rel="stylesheet">
<link href="/css/plugins/sweetalert/sweetalert.css"
	rel="stylesheet">

<script>
	var _roleId = "${role.id}";
</script>
</head>

<body class="gray-bg">
	<div class="row wrapper border-bottom white-bg page-heading">
		<div class="col-lg-10">
			<h2>角色权限管理</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">主页</a></li>
				<li><a href="/role/index.html">角色管理</a></li>
				<li><a>角色权限管理</a></li>
			</ol>
		</div>
		<div class="col-lg-2"></div>
	</div>

	<div class="wrapper wrapper-content animated fadeInRight">
		<div class="row">
			<div class="col-md-3">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5>菜单目录</h5>
					</div>
					<div class="ibox-content">
						<ul id="functionTree" class="ztree"></ul>
					</div>
				</div>
			</div>
			<div class="col-sm-9">
				<div class="ibox">
					<div class="ibox-title">
						<h5>角色信息</h5>
					</div>
					<div class="ibox-content">
						<div class="row">
							<form class="form-horizontal" id="roleOauthForm">
								<div class="form-group">
									<div class="form-group ">
										<label class="col-lg-3 control-label">角色名称：</label>
										<div class="col-lg-8">
											<span type="text" class="form-control">${role.name}</span>
										</div>
									</div>
								</div>
								<div class="hr-line-dashed"></div>
								<div class="form-group">
									<div class="col-sm-4 col-sm-offset-2">
										<button type="submit" class="btn btn-primary">保存</button>
										<button type="button" class="btn btn-white"
											onclick="history.go(-1);">返回</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script
	src="//cdn.bootcss.com/zTree.v3/3.5.24/js/jquery.ztree.all.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="/js/plugins/sweetalert/sweetalert.min.js"></script>

<script src="/js/pages/role/oauth.js"></script>
<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>
</html>

src/main/resources/templates/authorization/userIndex.ftl
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<title>用户授权</title>
<link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
<link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0" rel="stylesheet">
<link
	href="//cdn.bootcss.com/zTree.v3/3.5.24/css/zTreeStyle/zTreeStyle.css"
	rel="stylesheet">
<link href="/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="//cdn.bootcss.com/iCheck/1.0.2/skins/all.css"
	rel="stylesheet">

<script>
	var _adminId = "${admin.id}";
</script>
</head>

<body class="gray-bg">
	<div class="row wrapper border-bottom white-bg page-heading">
		<div class="col-lg-10">
			<h2>用户权限管理</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">主页</a></li>
				<li><a href="/admin/index.html">用户管理</a></li>
				<li><a>用户权限管理</a></li>
			</ol>
		</div>
		<div class="col-lg-2"></div>
	</div>

	<div class="wrapper wrapper-content animated fadeInRight">
		<div class="row">
			<div class="ibox">
				<div class="ibox-title">
					<h5>用户权限信息</h5>
				</div>
				<div class="ibox-content">
					<div class="row">
						<form class="form-horizontal" action="/admin/oauthsubmit"
							method="post" id="adminOauthForm">
							<input type="hidden" value="${admin.id}" name="id" />
							<div class="form-group">
								<div class="form-group ">
									<label class="col-lg-3 control-label">用户名称：</label>
									<div class="col-lg-8">
										<span type="text" class="form-control">${admin.user.username}</span>
									</div>
								</div>
							</div>
							<div class="hr-line-dashed"></div>
							<div class="form-group">
								<div class="form-group ">
									<label class="col-lg-3 control-label">角色选择：</label>
									<div class="col-lg-8">
										<#list roles as role> 
											<label class="radio-inline i-checks"> 
												<input type="checkbox" value="${role.id}" 
												<#list admin.roles as r>
													<#if r.id == role.id>
														checked
													</#if>
												</#list>
												 name="roleIds"> 
												<i></i> ${role.name}
											</label> 
										</#list>
									</div>
								</div>
							</div>
							<div class="hr-line-dashed"></div>
							<div class="form-group">
								<div class="col-sm-4 col-sm-offset-2">
									<button type="submit" class="btn btn-primary">保存</button>
									<button type="button" class="btn btn-white"
										onclick="history.go(-1);">返回</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script
	src="//cdn.bootcss.com/zTree.v3/3.5.24/js/jquery.ztree.all.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="/js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="//cdn.bootcss.com/iCheck/1.0.2/icheck.min.js"></script>
<script src="/js/pages/admin/oauth.js"></script>
<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>
</html>

src/main/resources/templates/calendar/addEvent.ftl
<div class="modal" id="addEvent" tabindex="-1" role="dialog"
	aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content animated bounceIn">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">×</span><span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title">添加事件</h4>
			</div>
			<form class="form-horizontal" id="manageEventForm" action="/event/saveOrUpdate.html" method="post">
				<small class="font-bold">
					<div class="modal-body">
                        <input name="id" id="idx" class="hide" value="">
                        <div class="form-group ">
							<label class="col-lg-3 control-label">日程内容(必填)：</label>
							<div class="col-lg-8">
								<textarea type="text" name="eventDesc" placeholder="请输入日程内容"  class="form-control"></textarea>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
						<button type="submit" class="btn btn-primary">保存</button>
					</div>
				</small>
			</form>
		</div>
		<small class="font-bold"> </small>
	</div>
	<small class="font-bold"> </small>
</div>

src/main/resources/templates/calendar/index.ftl
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> - 日历</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="shortcut icon" href="favicon.ico"> 
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.css?v=4.4.0" rel="stylesheet">
    <link href="/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/css/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
    <link href="/css/plugins/fullcalendar/fullcalendar.print.css" rel="stylesheet"  media='print'>
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="gray-bg">
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInDown">
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>课程</h5>
                    </div>
                    <div class="ibox-content">
                        <div id='external-events'>
                            <p>可拖动的活动</p>
                            <div class='external-event navy-bg'>大班课</div>
                            <div class='external-event navy-bg'>小班课</div>
                            <div class='external-event navy-bg'>中班课</div>
                            
                            <p class="m-t">
                                <input type='checkbox' id='drop-remove' class="i-checks" checked />
                                <label for='drop-remove'>移动后删除</label>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-9">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>课程日历</h5>
                    </div>
                    <div class="ibox-content">
                        <div id="calendar"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <#include "addEvent.ftl">
    <!-- 全局js -->
    <script src="/js/jquery.min.js?v=2.1.4"></script>
    <script src="/js/bootstrap.min.js?v=3.3.6"></script>
    <!-- 自定义js -->
    <script src="/js/content.js?v=1.0.0"></script>
    <script src="/js/jquery-ui.custom.min.js"></script>
    <!-- iCheck -->
    <script src="/js/plugins/iCheck/icheck.min.js"></script>
    <!-- Full Calendar -->
    <script src='/js/plugins/fullcalendar/moment.min.js'></script>
    <script src="/js/plugins/fullcalendar/fullcalendar.js"></script>
    <script src='/js/plugins/fullcalendar/locale-all.js'></script>
    <script src="/js/pages/calendar/index.js"></script>
</body>

</html>

src/main/resources/templates/decorators/breadcrumb.ftl
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>${(function.name)!}</h2>
        <ol class="breadcrumb">
            <li><a href="index.htm">主页</a></li>
            <li><a>${(function.parent.name)!}</a></li>
            <li><a>${(function.name)!}</a></li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

src/main/resources/templates/error.ftl
<!DOCTYPE html>
<html lang="en">
<body>Something wrong: ${status} ${error}
</body>
</html>

src/main/resources/templates/function/index.ftl
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>目录菜单管理</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="shortcut icon" href="favicon.ico">
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.css?v=4.4.0" rel="stylesheet">
    <!-- Data Tables -->
    <link href="/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">
    <link href="/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">

</head>

<body class="gray-bg">
<@breadcrumb />
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>目录菜单管理</h5>
                </div>
                <div class="ibox-content">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-success" data-toggle="modal" id="addFunctionButton">
                            <i class="fa fa-plus" aria-hidden="true"></i> 添加分类
                        </button>
                    </div>
                    <hr>
                    <table class="table table-striped table-bordered table-hover dataTables-example function-table">
                        <thead>
                        <tr>
                            <th>唯一标识</th>
                            <th>名称</th>
                            <th>上级名称</th>
                            <th>授权</th>
                            <th>类型</th>
                            <th>url地址</th>
                            <th>是否有效</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <#list functions as function>
                        <tr>
                            <td>${function.id}</td>
                            <td>${function.name}</td>
                            <td>${(function.parent.name)!''}</td>
                            <td>${function.shiroPermission}</td>
                            <td><#if function.type==1>分类
                            <#elseif function.type==2>菜单
                            <#elseif function.type == 3>链接
                            <#elseif function.type == 4>按钮
                            <#else>其他
                            </#if></td>
                            <td>${function.url!''}</td>
                            <td>${function.active?string('有效','无效')}</td>
                            <td>
                                <a xhref="/function/remove?id=${function.id}" class="function-remove" title="删除操作"><i
                                        class="glyphicon glyphicon-remove"></i>
                                </a>
                                <a jsonStr="{'id':'${function.id}','name':'${function.name}','type':'${function.type}','url':'${function.url!''}','pid':'${(function.parent.id)!''}','pname':'${(function.parent.name)!''}','shiroPermission':'${function.shiroPermission}'}"
                                   class="function-update"
                                   title="修改操作">
                                    <i class="glyphicon glyphicon-edit"></i>
                                </a>
                                <a jsonStr="{'type':'${function.type + 1}','pid':'${function.id}','pname':'${function.name}'}"
                                   class="function-addChild"
                                   title="添加子类"><i class="fa fa-plus"></i>
                                </a>
                            </td>
                        </tr>
                        </#list>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<#include "addFunction.ftl">
<!-- 全局js -->
<script src="/js/jquery.min.js?v=2.1.4"></script>
<script src="/js/bootstrap.min.js?v=3.3.6"></script>
<script src="/js/plugins/jeditable/jquery.jeditable.js"></script>
<!-- Data Tables -->
<script src="/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<!-- 自定义js -->
<script src="/js/content.js?v=1.0.0"></script>
<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>
<!-- Page-Level Scripts -->
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/jquery.validate.min.js"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/localization/messages_zh.js"></script>
<script src="/js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="/js/pages/function/index.js"></script>
</body>
</html>